---

- name: Install HHVM
  yum: name=https://github.com/hkirsman/hhvm_centos7_rpms/raw/b9569aec30f7855d180966a3bc9d6ca2e78e7604/hhvm-3.12.1.el7.centos.x86_64.rpm state=present

- name: Copy configurations to /etc/hhvm/
  file: path=/etc/hhvm state=directory
- copy:
    src=etc/hhvm/{{ item }}
    dest=/etc/hhvm/{{ item }}
  with_items:
    - php.ini
    - server.ini

- name: Set up service
  copy:
    src=etc/init.d/hhvm
    dest=/etc/init.d/hhvm
    mode="u+rwx,g+rx,o+rx"

- name: Create logs folder
  file: path=/var/log/hhvm state=directory owner=nginx group=nginx

- name: Create run folder
  file: path=/var/run/hhvm state=directory owner=nginx group=nginx

- name: Add HHVM to service
  shell: chkconfig --add hhvm
- shell: chkconfig hhvm on

- name: Start/restart HHVM
  service: name=hhvm state=restarted
